name: Dependabot auto-label
on: 
  - pull_request
  - workflow_dispatch

permissions:
  pull-requests: write
  issues: write
  repository-projects: write

jobs:
  dependabot:
    runs-on: ubuntu-latest
    if: ${{ github.actor == 'dependabot[bot]' }}
    steps:
      - name: Dependabot metadata
        id: metadata
        uses: dependabot/fetch-metadata@v1
        with:
          github-token: "${{ secrets.GITHUB_TOKEN }}"
      - name: Add a label for dependency updates
        run: gh pr edit "$PR_URL" --add-label "santhosh-test"
        env:
          PR_URL: ${{github.event.pull_request.html_url}}