name: Merge Dependabot Pull Requests

on:
  pull_request:
    types: [closed]
  workflow_dispatch:  

jobs:
  merge_dependabot_pull_requests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Merge pull request
        uses: juliangruber/merge-pull-request-action@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
