name: Merge Dependabot Pull Requests

on:
  pull_request:
    types: [closed]
  workflow_dispatch: 

permissions:
  id-token: write
  contents: read
  issues: write
  pull-requests: write   

jobs:
  merge_dependabot_pull_requests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Merge pull request
        uses: pascalgn/automerge-action@v0.14.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
