name: Merge Dependabot Pull Requests

on:
  pull_request:
    types: [closed]
  workflow_dispatch:  

jobs:
  merge_dependabot_pull_requests:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged && contains(github.event.pull_request.head.ref, 'dependabot/')

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Merge pull request
        uses: pascalgn/automerge-action@v0.14.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
