name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

  steps:
  - run:
      npm i
      cd frontend
      npm i
      npm run build   